### ISSUE TITLE
You can't shut me up while I'm loading!

### ISSUE THREAD

**Issue by mutantcornholio** [themylogin/3G-Player#6]
Have you've ever seen a song that is loading? 
If you did, you know what I'm talking about.
They're loud, angry, fierceful.
You can't shut them up — if you try, they'll hit back hard with the next data chunk.
All you can do is crawl into your tiny place of self-comfort, turn the volume down and hope that it will stop fast enough.

**Comment by themylogin** [comment]
Fixed
